language: node_js
sudo: required
dist: trusty
git:
  depth: 1

before_install:
  # Key for cran trusty ppa
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 51716619E084DAB9

  # Add repositories
  - echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" | sudo tee -a /etc/apt/sources.list
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo add-apt-repository -y ppa:fish-shell/release-2
  - sudo apt-get update -qq

  # Dependencies
  - sudo apt-get install libv8-3.14-dev r-base r-base-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev fish -y

node_js:
  - 7

cache: yarn

env:
  global:
  - ENCRYPTION_LABEL: dce9ae5740a9

script: bash ./travis-main.sh
