#!/usr/bin/env bash

set -e

if [ "$TRAVIS_COMMIT_MESSAGE" == "[TRAVIS] Autogenerated files from travis" ]; then
    echo "This is an auto commit from travis. Not doing anything."
    exit 0
fi

echo "> Running tests"

# Test data
# yarn
# yarn run test

if [ "$TRAVIS_BRANCH" != "master" ]; then
    echo "Not on master. Not doing anything else."
    exit 0
fi

# Save some useful information
REPO=`git config remote.origin.url`
SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
SHA=`git rev-parse --verify HEAD`

# Setup credentials
git config user.name "CI auto deploy"
git config user.email "abhinav.tushar.vs@gmail.com"
ENCRYPTED_KEY_VAR="encrypted_${ENCRYPTION_LABEL}_key"
ENCRYPTED_IV_VAR="encrypted_${ENCRYPTION_LABEL}_iv"
ENCRYPTED_KEY=${!ENCRYPTED_KEY_VAR}
ENCRYPTED_IV=${!ENCRYPTED_IV_VAR}
openssl aes-256-cbc -K $ENCRYPTED_KEY -iv $ENCRYPTED_IV -in deploy_key.enc -out deploy_key -d
chmod 600 deploy_key
eval `ssh-agent -s`
ssh-add deploy_key

if [ "$TRAVIS_COMMIT_MESSAGE" == "[TRAVIS] Generate scores" ]; then
    echo "This is a trigger to generate scores."
    # Generate ./scores/scores.csv
    yarn run generate-scores
    # Generate model id mappings
    yarn run generate-id-mappings
    # Fix model metadata formatting
    yarn run format-metadata

    echo "> Pushing formatted metadata, scores and model-id-mapping csvs"
    git add ./scores/scores.csv
    git add ./csv-error.log
    git add ./csv-blacklist.yaml
    git add ./scores/scores.csv
    git add ./model-forecasts/component-models/complete-modelids.csv
    git add ./model-forecasts/component-models/model-id-map.csv
    git add ./model-forecasts/*/*/metadata.txt
    git diff-index --quiet HEAD || git commit -m "[TRAVIS] Autogenerated files from travis"
    git push $SSH_REPO HEAD:master
fi

# Setup R now
# Download pinned [pkr](https://github.com/lepisma/pkr) version
echo "> Setting up R dependencies"
wget https://raw.githubusercontent.com/lepisma/pkr/d4fed8349bec44bd058e94063a9280f85284ff0a/pkr
sudo chmod +x pkr
sudo Rscript -e "install.packages(c('packrat', 'docopt', 'devtools'), repos = 'http://cran.us.r-project.org')"
sudo ./pkr --version
sudo ./pkr in --file pkrfile --global

echo "> Building visualizer"
# Go back and build flusight
git checkout gh-pages || git checkout --orphan gh-pages
cd ./flusight-deploy
bash ./0-init-flusight.sh
bash ./1-build-flusight.sh
cd .. # in repo root now

# Remove CSVs
find . -name "*.csv" -type f -delete

git add .
git commit -m "[TRAVIS] Auto deploy to GitHub pages from travis: ${SHA}"

echo "> Pushing visualizer to gh-pages"
# Push to gh-pages
git push $SSH_REPO gh-pages --force
ssh-agent -k
