#mcandrew;

PYTHON := python3

../weights/static-regularized-weights.csv: create_static_regularized_weights.py
	$(PYTHON) create_static_regularized_weights.py && \
	echo "completed without error"




