---
title: "Seasonal Target Heatmap"
author: "Evan Moore"
date: "April 20, 2018"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.height = 8, fig.width = 12)
```

## Seasonal Forecast Targets by Region

```{r}
library(cdcfluview)
library(FluSight)
library(MMWRweek)
library(RColorBrewer)
library(ggpubr)
library(dplyr)
library(ggplot2)
theme_set(theme_minimal())

THIS_SEASON <- "2017/2018"
FORECAST_EW <- MMWRweek(as.Date(Sys.Date()))[1,2] - 2

get_weeks <- function(FORECAST_EW){
  if (FORECAST_EW >=40) {
    past_weeks <- c(43:FORECAST_EW)  
  } else {
    past_weeks <- c(43:52, 1:FORECAST_EW)
  }
  return(past_weeks)
}

weeks <- get_weeks(FORECAST_EW)

#heatmaps of weekly targets by region
targets <- c("Season onset", "Season peak percentage", "Season peak week")

#df of peak percentage
for (targ in targets){
  for(week in weeks) {
    if (week %in% 43:52){
      file_path <- paste("../model-forecasts/real-time-ensemble-models/",
                         "target-type-based-weights/EW",
                         as.character(week),
                         "-2017-target-type-based-weights.csv", 
                         sep = "")
    } else if (week %in% 1:9){
      file_path <- paste("../model-forecasts/real-time-ensemble-models/",
                         "target-type-based-weights/EW0",
                         as.character(week),
                         "-2018-target-type-based-weights.csv", 
                         sep = "")
    }  else {
      file_path <- paste("../model-forecasts/real-time-ensemble-models/",
                         "target-type-based-weights/EW",
                         as.character(week),
                         "-2018-target-type-based-weights.csv", 
                         sep = "")
    }
    d <- read_entry(file_path)
    d_peak <- subset(d, target == targ & type == "Bin")
    if (targ %in% c("Season onset", "Season peak week")){
      d_peak$bin_start_incl <- factor(substr(d_peak$bin_start_incl, 1, 
                                             nchar(d_peak$bin_start_incl) - 2),
                                      levels=paste(c(40:52, 1:20), sep = ""))
    }  
    if (week == 43) {
      df_peak <- d_peak
      next
    }
    df_peak <- rbind(df_peak, d_peak)
  }
  assign(targ, df_peak)
}

palette <- colorRampPalette(c("white","grey", "darkblue"))
cuts <- c(0, 0.01, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1)

plot_heatmap_peak_2 <- function(data) {
  data <- na.omit(data)
  if (data[1, ]$target == "Season peak percentage") {
    data$bins2 <- cut(
      as.numeric(data$bin_start_incl),
      breaks = c(seq(0, 12, by = .5), Inf),
      right = FALSE
    )
    data <-
      data %>% group_by(bins2, forecast_week, location) %>% mutate(summed_vals = sum(value))
    data$value_bin <- cut(data$summed_vals, breaks = cuts)
    return (
      ggplot(data, aes(
        x = factor(forecast_week, levels = c(43:52, 1:FORECAST_EW)), y = bins2
      )) +
        geom_tile(aes(fill = value_bin)) + scale_fill_brewer(palette(10)) +
        labs(y = "wILI %", x = "Forecast Week") +
        ggtitle(data[1, ]$target) +
        guides(fill = guide_legend(title = "Probability"))
    )
  } else {
    data$value_bin <- cut(data$value, breaks = cuts)
    return (
      ggplot(data, aes(
        x = factor(forecast_week, levels = c(43:52, 1:FORECAST_EW)), y = bin_start_incl
      )) +
        geom_tile(aes(fill = value_bin)) + scale_fill_brewer(palette(10)) +
        labs(y = "Week", x = "Forecast Week") +
        ggtitle(data[1, ]$target) +
        guides(fill = guide_legend(title = "Probability"))
    )
  }
}

plot_heatmaps_peak <- function(onset, peak_wk, peak_per, region) {
  p1 <-
    plot_heatmap_peak_2(onset %>% dplyr::filter(location == region))
  p2 <-
    plot_heatmap_peak_2(peak_wk %>% dplyr::filter(location == region))
  p3 <-
    plot_heatmap_peak_2(peak_per %>% dplyr::filter(location == region))
  fig <- ggarrange(
    p1,
    p2,
    p3,
    common.legend = T,
    legend = "right",
    ncol = 3
  )
  return(annotate_figure(fig, top = text_grob(
    region,
    color = "black",
    face = "bold",
    size = 14
  )))
}

```

# US National
```{r}
plot_heatmaps_peak(`Season onset`,
                   `Season peak week`,
                   `Season peak percentage`,
                   "US National")
```

# HHS Region 1
```{r}
plot_heatmaps_peak(`Season onset`,
                   `Season peak week`,
                   `Season peak percentage`,
                   "HHS Region 1")
```

# HHS Region 2
```{r}
plot_heatmaps_peak(`Season onset`,
                   `Season peak week`,
                   `Season peak percentage`,
                   "HHS Region 2")
```

# HHS Region 3
```{r}
plot_heatmaps_peak(`Season onset`,
                   `Season peak week`,
                   `Season peak percentage`,
                   "HHS Region 3")
```

# HHS Region 4
```{r}
plot_heatmaps_peak(`Season onset`,
                   `Season peak week`,
                   `Season peak percentage`,
                   "HHS Region 4")
```

# HHS Region 5
```{r}
plot_heatmaps_peak(`Season onset`,
                   `Season peak week`,
                   `Season peak percentage`,
                   "HHS Region 5")
```

# HHS Region 6
```{r}
plot_heatmaps_peak(`Season onset`,
                   `Season peak week`,
                   `Season peak percentage`,
                   "HHS Region 6")
```

# HHS Region 7
```{r}
plot_heatmaps_peak(`Season onset`,
                   `Season peak week`,
                   `Season peak percentage`,
                   "HHS Region 7")
```

# HHS Region 8
```{r}
plot_heatmaps_peak(`Season onset`,
                   `Season peak week`,
                   `Season peak percentage`,
                   "HHS Region 8")
```

# HHS Region 9
```{r}
plot_heatmaps_peak(`Season onset`,
                   `Season peak week`,
                   `Season peak percentage`,
                   "HHS Region 9")
```

# HHS Region 10
```{r}
plot_heatmaps_peak(`Season onset`,
                   `Season peak week`,
                   `Season peak percentage`,
                   "HHS Region 10")
```
```