# Items used for branding
branding:
  title: "FluSight Network"
  parent: ""
  description: "CDC FluSight Network Collaborative Ensemble"
  imageUrl: ""
  aboutUrl: "http://reichlab.io/2017/11/28/flusight-ensemble.html"
  appUrl: "http://flusightnetwork.io/"
  sourceUrl: "https://github.com/FluSightNetwork/cdc-flusight-ensemble"
  parentUrl: "https://github.com/FluSightNetwork/cdc-flusight-ensemble/blob/master/README.md"
